#!/usr/bin/env python3
"""Render the declared compatibility contract and optional CI execution evidence."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from gms_mcp.client_registry import CLIENT_SPECS  # noqa: E402
from gms_mcp.install_support.common import ONBOARDING_PROFILES, SUPPORTED_TOOLSETS  # noqa: E402


EVIDENCE_SUITES = (
    "cli/tests/python/test_install_parity.py",
    "cli/tests/python/test_install_polish.py",
    "cli/tests/python/test_mcp_protocol_compatibility.py",
    "cli/tests/python/test_mcp_stdio_transport_regression.py",
    "cli/tests/python/test_mcp_v2_http_transport.py",
)


def render_matrix() -> str:
    rows = []
    for spec in CLIENT_SPECS:
        aliases = ", ".join(f"`{alias}`" for alias in spec.aliases) or "-"
        rows.append(
            "| `{key}` | {aliases} | {workspace} | {global_scope} | `{format}` |".format(
                key=spec.key,
                aliases=aliases,
                workspace="yes" if spec.workspace_supported else "no",
                global_scope="yes" if spec.global_supported else "no",
                format=spec.config_format,
            )
        )
    toolsets = ", ".join(f"`{toolset}`" for toolset in SUPPORTED_TOOLSETS)
    profiles = ", ".join(f"`{profile}`" for profile in ONBOARDING_PROFILES)
    evidence = "\n".join(f"- `{path}`" for path in EVIDENCE_SUITES)
    return f"""# Compatibility Matrix

This file is generated by `scripts/generate_compatibility_matrix.py`. It records declared installer support and repository test coverage; it does not certify a third-party client release.

## Declared installer support

| Client | Aliases | Workspace | Global | Config format |
|---|---|---:|---:|---|
{chr(10).join(rows)}

## Declared onboarding profiles

Canonical setup accepts {profiles}. `safe` is the default and exposes a read-only `core` surface with project mutators omitted. `standard` uses the complete `core` surface. `full` enables `all` toolsets. `--toolsets` overrides `standard` or `full`; safe accepts only `core`.

Supported explicit toolsets: {toolsets}, or `all`.

## Executed-evidence contract

The following suites are the declared evidence sources. CI publishes a separate sanitized evidence JSON only after its test command has run. This matrix intentionally has no "verified as of" timestamp because declarations are not live client certification.

{evidence}
"""


def build_evidence(*, executed_evidence: list[str], verified_as_of: str | None) -> dict[str, object]:
    payload: dict[str, object] = {
        "schema_version": 1,
        "declarations": {
            "clients": [spec.key for spec in CLIENT_SPECS],
            "onboarding_profiles": list(ONBOARDING_PROFILES),
            "supported_toolsets": list(SUPPORTED_TOOLSETS),
            "evidence_suites": list(EVIDENCE_SUITES),
        },
        "executed_evidence": sorted(set(executed_evidence)),
    }
    if verified_as_of is not None:
        payload["verified_as_of"] = verified_as_of
    return payload


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=REPO_ROOT / "documentation" / "COMPATIBILITY_MATRIX.md")
    parser.add_argument("--check", action="store_true", help="Fail when --output differs from generated content.")
    parser.add_argument("--evidence-output", type=Path, help="Write a sanitized CI evidence JSON file.")
    parser.add_argument("--executed-evidence", action="append", default=[], help="Completed CI evidence identifier.")
    parser.add_argument(
        "--verified-as-of",
        help="CI-supplied revision or timestamp. It is emitted only in --evidence-output, never the matrix.",
    )
    args = parser.parse_args(argv)

    matrix = render_matrix()
    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            parser.exit(1, f"compatibility matrix is missing: {args.output}\n")
        if current != matrix:
            parser.exit(1, f"compatibility matrix is stale: run {Path(__file__).as_posix()}\n")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(matrix, encoding="utf-8")

    if args.evidence_output is not None:
        evidence = build_evidence(executed_evidence=args.executed_evidence, verified_as_of=args.verified_as_of)
        args.evidence_output.parent.mkdir(parents=True, exist_ok=True)
        args.evidence_output.write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
